# mbedTLS library sources for Sagrado Jabber (TLS 1.2 client only).
MBEDTLS_SRC_DIR := apps/jabber/third_party/mbedtls/library
MBEDTLS_SRCS := \
  $(MBEDTLS_SRC_DIR)/aes.c \
  $(MBEDTLS_SRC_DIR)/aesni.c \
  $(MBEDTLS_SRC_DIR)/aesce.c \
  $(MBEDTLS_SRC_DIR)/asn1parse.c \
  $(MBEDTLS_SRC_DIR)/asn1write.c \
  $(MBEDTLS_SRC_DIR)/base64.c \
  $(MBEDTLS_SRC_DIR)/bignum.c \
  $(MBEDTLS_SRC_DIR)/bignum_core.c \
  $(MBEDTLS_SRC_DIR)/bignum_mod.c \
  $(MBEDTLS_SRC_DIR)/bignum_mod_raw.c \
  $(MBEDTLS_SRC_DIR)/block_cipher.c \
  $(MBEDTLS_SRC_DIR)/ccm.c \
  $(MBEDTLS_SRC_DIR)/chacha20.c \
  $(MBEDTLS_SRC_DIR)/chachapoly.c \
  $(MBEDTLS_SRC_DIR)/cipher.c \
  $(MBEDTLS_SRC_DIR)/cipher_wrap.c \
  $(MBEDTLS_SRC_DIR)/cmac.c \
  $(MBEDTLS_SRC_DIR)/constant_time.c \
  $(MBEDTLS_SRC_DIR)/ctr_drbg.c \
  $(MBEDTLS_SRC_DIR)/dhm.c \
  $(MBEDTLS_SRC_DIR)/ecdh.c \
  $(MBEDTLS_SRC_DIR)/ecdsa.c \
  $(MBEDTLS_SRC_DIR)/ecp.c \
  $(MBEDTLS_SRC_DIR)/ecp_curves.c \
  $(MBEDTLS_SRC_DIR)/ecp_curves_new.c \
  $(MBEDTLS_SRC_DIR)/entropy.c \
  $(MBEDTLS_SRC_DIR)/entropy_poll.c \
  $(MBEDTLS_SRC_DIR)/error.c \
  $(MBEDTLS_SRC_DIR)/gcm.c \
  $(MBEDTLS_SRC_DIR)/hkdf.c \
  $(MBEDTLS_SRC_DIR)/hmac_drbg.c \
  $(MBEDTLS_SRC_DIR)/md.c \
  $(MBEDTLS_SRC_DIR)/md5.c \
  $(MBEDTLS_SRC_DIR)/oid.c \
  $(MBEDTLS_SRC_DIR)/pem.c \
  $(MBEDTLS_SRC_DIR)/pk.c \
  $(MBEDTLS_SRC_DIR)/pk_ecc.c \
  $(MBEDTLS_SRC_DIR)/pk_wrap.c \
  $(MBEDTLS_SRC_DIR)/pkcs12.c \
  $(MBEDTLS_SRC_DIR)/pkcs5.c \
  $(MBEDTLS_SRC_DIR)/pkparse.c \
  $(MBEDTLS_SRC_DIR)/platform.c \
  $(MBEDTLS_SRC_DIR)/platform_util.c \
  $(MBEDTLS_SRC_DIR)/poly1305.c \
  $(MBEDTLS_SRC_DIR)/rsa.c \
  $(MBEDTLS_SRC_DIR)/rsa_alt_helpers.c \
  $(MBEDTLS_SRC_DIR)/sha1.c \
  $(MBEDTLS_SRC_DIR)/sha256.c \
  $(MBEDTLS_SRC_DIR)/sha512.c \
  $(MBEDTLS_SRC_DIR)/ssl_ciphersuites.c \
  $(MBEDTLS_SRC_DIR)/ssl_client.c \
  $(MBEDTLS_SRC_DIR)/ssl_debug_helpers_generated.c \
  $(MBEDTLS_SRC_DIR)/ssl_msg.c \
  $(MBEDTLS_SRC_DIR)/ssl_tls.c \
  $(MBEDTLS_SRC_DIR)/ssl_tls12_client.c \
  $(MBEDTLS_SRC_DIR)/version.c \
  $(MBEDTLS_SRC_DIR)/x509.c \
  $(MBEDTLS_SRC_DIR)/x509_crt.c
